### PR TITLE
bblfshd. Add SupportedLanguages method

### PR DESCRIPTION
**Pull request by dpordomingo**
Required by https://github.com/bblfsh/sdk/issues/253
Blocked by ~https://github.com/bblfsh/sdk/pull/259~
Blocks https://github.com/bblfsh/client-go/pull/57

(see https://github.com/bblfsh/sdk/pull/259 description)

### CODE REVIEW

**Comment by dpordomingo** [comment]
Let me know @dennwc if I can fix something to get a green tick ;)
Feel free to push against my branch if you prefer doing it on your own :dagger:

**Comment by dennwc** [comment]
@dpordomingo I'm just waiting for https://github.com/bblfsh/sdk/pull/259 to be merged, so we can update this PR's vendor directory with an updated SDK.

**Comment by dpordomingo** [comment]
Oh, yes, right; I pushed the `sdk-candidate` into `vendor` for Travis sake, but it will need to be updated as soon as these PR dependencies are merged :dancing_men: 
I already considered it (it will be also needed at https://github.com/bblfsh/dashboard/pull/133)

**Comment by dpordomingo** [comment]
Adding some tests; I'll ping here once they're ready (if I'm able to add them :crossed_fingers: )

**Comment by dpordomingo** [comment]
Rebased, squashed and two new commits added:
- a6b2e29  `vendor/gopkg.in/bblfsh/sdk.v1` was updated as [required](https://github.com/bblfsh/bblfshd/pull/167#issuecomment-393840581) by @dennwc
- 45d9048 some tests were added to keep current code coverage ratio

ready to be merged now

**Pull request merged**
